[project]
name = 'Blockchain-Based-Brand-Management-Protection-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-protection]
path = 'contracts/asset-protection.clar'
clarity_version = 2
epoch = 2.5

[contracts.enforcement-coordination]
path = 'contracts/enforcement-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
